export const B2C_BONUS_PROJECTS = [
	"stelario",
	"winlegends",
	"smokace",
	"windetta",
	"hexabet",
	"betflare",
	"megarich",
	"casabet",
	"rioace",
	"lollyspins",
	"corsaza",
	"spinmills",
	"velwins",
	"crixcasino",
	"spinko",
	"dionyx",
	"kairosbet",
	"nikaspin",
	"spartibet",
	"olymposwin",
	"spinfyre",
	"vibespins",
	"winserra",
	"casikora",
	"spintado",
	"rollizor",
	"betnaro",
	"7oasis",
	"winbandits",
	"spintitans",
];

export const BONUS_PROJECT_ALIASES: Record<string, string[]> = {
	SA: ["smokace"],
	ST: ["stelario"],
	WL: ["winlegends"],
	WD: ["windetta"],
	HX: ["hexabet"],
	BEF: ["betflare"],
	MR: ["megarich"],
	CAB: ["casabet"],
	RA: ["rioace"],
	LOL: ["lollyspins"],
	COR: ["corsaza"],
	HL: ["hashlucky"],
	SPM: ["spinmills"],
	NS: ["nikaspin"],
	CJ: ["casinojoy", "crixcasino"],
	CC: ["cosmicslot", "crixcasino"],
	SPI: ["spinko"],
	DN: ["dionyx"],
	KIB: ["kairosbet"],
	OAS: ["olymposwin", "7oasis"],
	IG: ["ignibet"],
	EG: ["egogames"],
	CS: ["cosmicslot"],
	GZ: ["gamblezen"],
	JB: ["jettbet"],
	BZ: ["blitz-bet", "blitzbet"],
	CB: ["casperbets"],
	LH: ["luckyhour"],
	RL: ["rollino", "rollizor"],
};
