import type { Bind } from "@/entities/bind";
import type { KnowledgeCategory, KnowledgeFolder } from "@/entities/knowledge";
import { type KnowledgeSnapshot, useKnowledgeStore } from "@/store";

import { backupRequest, exportKnowledgeJson } from "./knowledge-api";

export interface KnowledgeDatabase
	extends Partial<
		Pick<
			KnowledgeSnapshot,
			| "selectedCategory"
			| "selectedFolder"
			| "selectedBind"
			| "expandedFolders"
			| "language"
			| "search"
			| "favorites"
			| "recent"
			| "favoriteFolders"
			| "recentFolders"
			| "openedTabs"
			| "pinnedTabs"
			| "activeTab"
		>
	> {
	categories: KnowledgeCategory[];
	folders: KnowledgeFolder[];
	binds: Bind[];
}

type StoredKnowledge = KnowledgeDatabase & {
	version?: number;
};

export function clone<T>(value: T): T {
	return JSON.parse(JSON.stringify(value)) as T;
}

export function now() {
	return new Date().toISOString();
}

export function normalizeDatabase(
	database: Partial<StoredKnowledge>,
): KnowledgeDatabase {
	const categories = Array.isArray(database.categories)
		? database.categories.map((category) => ({
				...category,
				ownerId:
					category.ownerId === null
						? null
						: typeof category.ownerId === "string"
							? category.ownerId
							: undefined,
			}))
		: [];
	const folders = Array.isArray(database.folders)
		? database.folders.map((folder) => ({
				...folder,
				ownerId:
					folder.ownerId === null
						? null
						: typeof folder.ownerId === "string"
							? folder.ownerId
							: undefined,
			}))
		: [];
	const binds = Array.isArray(database.binds)
		? database.binds.map((bind) => ({
				...bind,
				ownerId:
					bind.ownerId === null
						? null
						: typeof bind.ownerId === "string"
							? bind.ownerId
							: undefined,
				sourceBindId:
					typeof bind.sourceBindId === "string" ? bind.sourceBindId : undefined,
				sourceHash:
					typeof bind.sourceHash === "string" ? bind.sourceHash : undefined,
				importBatchId:
					typeof bind.importBatchId === "string"
						? bind.importBatchId
						: undefined,
				imported: Boolean(bind.imported),
				order: typeof bind.order === "number" ? bind.order : undefined,
				tags: Array.isArray(bind.tags) ? bind.tags : [],
				translations: Array.isArray(bind.translations) ? bind.translations : [],
				history: Array.isArray(bind.history) ? bind.history : [],
				pinned: Boolean(bind.pinned),
				copyCount: typeof bind.copyCount === "number" ? bind.copyCount : 0,
				lastCopiedAt:
					typeof bind.lastCopiedAt === "string" ? bind.lastCopiedAt : undefined,
				aiGenerated: bind.aiGenerated,
				aiTranslated: bind.aiTranslated,
				aiSummary:
					typeof bind.aiSummary === "string" ? bind.aiSummary : undefined,
				favorite: Boolean(bind.favorite),
				archived: Boolean(bind.archived),
				createdAt: bind.createdAt || now(),
				updatedAt: bind.updatedAt || now(),
			}))
		: [];

	return {
		categories,
		folders,
		binds,
		expandedFolders: Array.isArray(database.expandedFolders)
			? database.expandedFolders
			: [],
		language: database.language ?? "ru",
		search: database.search ?? "",
		favorites: Array.isArray(database.favorites)
			? database.favorites
			: binds.filter((bind) => bind.favorite).map((bind) => bind.id),
		recent: Array.isArray(database.recent) ? database.recent : [],
		favoriteFolders: Array.isArray(database.favoriteFolders)
			? database.favoriteFolders
			: [],
		recentFolders: Array.isArray(database.recentFolders)
			? database.recentFolders
			: [],
		openedTabs: Array.isArray(database.openedTabs) ? database.openedTabs : [],
		pinnedTabs: Array.isArray(database.pinnedTabs) ? database.pinnedTabs : [],
		activeTab: database.activeTab,
		selectedBind: database.selectedBind,
		selectedCategory: database.selectedCategory,
		selectedFolder: database.selectedFolder,
	};
}

// Compatibility runtime snapshot; backups must be generated by the server below.
export function getKnowledgeSnapshot(): KnowledgeDatabase {
	const state = useKnowledgeStore.getState();

	return {
		categories: state.categories,
		folders: state.folders,
		binds: state.binds,
		selectedCategory: state.selectedCategory,
		selectedFolder: state.selectedFolder,
		selectedBind: state.selectedBind,
		expandedFolders: state.expandedFolders,
		language: state.language,
		search: state.search,
		favorites: state.favorites,
		recent: state.recent,
		favoriteFolders: state.favoriteFolders,
		recentFolders: state.recentFolders,
		openedTabs: state.openedTabs,
		pinnedTabs: state.pinnedTabs,
		activeTab: state.activeTab,
	};
}

export interface BackupPreview {
	token: string;
	counts: Record<
		"categories" | "folders" | "binds",
		{ add: number; existing: number }
	>;
	existingIds: Record<"categories" | "folders" | "binds", string[]>;
}

function parseFile(payload: string) {
	if (payload.length > 3_000_000)
		throw new Error("Файл превышает лимит импорта");
	try {
		return JSON.parse(payload) as unknown;
	} catch {
		throw new Error("Некорректный JSON-файл");
	}
}

export const supportOSExportService = {
	async exportJson(): Promise<string> {
		return exportKnowledgeJson();
	},
	async previewImport(payload: string): Promise<BackupPreview> {
		return backupRequest({
			action: "backup-preview",
			payload: parseFile(payload),
		});
	},
	async applyImport(
		payload: string,
		preview: BackupPreview,
		mode: "merge" | "upsert",
	) {
		return backupRequest({
			action: "backup-apply",
			payload: parseFile(payload),
			token: preview.token,
			mode,
		});
	},
};
