import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import {it,expect} from 'vitest';
it('isolates sessions, expires proofs, denies replay and enforces RLS with admin-reviewed enrollment',async()=>{
 const pg=new PGlite();
 try {
  await pg.exec("create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_app_meta_data jsonb,raw_user_meta_data jsonb,is_anonymous boolean default false);create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;grant usage on schema auth to authenticated;grant execute on function auth.uid(),auth.jwt() to authenticated;");
  for(const file of ['../supabase/schema.sql','../supabase/migrations/20260923081810_telegram_registration.sql','../supabase/migrations/20260923192252_telegram_login_2fa.sql'])await pg.exec(await readFile(new URL(file,import.meta.url),'utf8'));
  const user='11111111-1111-4111-8111-111111111111',sid='22222222-2222-4222-8222-222222222222',sid2='33333333-3333-4333-8333-333333333333',id='44444444-4444-4444-8444-444444444444',legacy='55555555-5555-4555-8555-555555555555';
  await pg.query('insert into auth.users(id,email) values($1,$2),($3,$4)',[user,'test@example.test',legacy,'legacy@example.test']);
  await pg.query('insert into auth.sessions(id,user_id) values($1,$2),($3,$2),($4,$5)',[sid,user,sid2,id,legacy]);
  await pg.query("insert into public.supportos_telegram_links(user_id,telegram_id,source) values($1,123,'registration')",[user]);
  const rpc=async(name,args)=>(await pg.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) value`,args)).rows[0].value;
  const state=(u=user,s=sid)=>rpc('supportos_tg_login_state',[u,s]);
  expect(await state()).toMatchObject({status:'required'});
  expect(await state(user,id)).toMatchObject({status:'invalid_session'});
  expect(await rpc('supportos_tg_login_begin',[user,sid,id,'a'.repeat(64),'Browser','ip',false])).toMatchObject({status:'pending',send:true});
  expect(await rpc('supportos_tg_login_begin',[user,sid,id,'b'.repeat(64),'Browser','ip',true])).toEqual({error:'rate_limit'});
  expect(await rpc('supportos_tg_login_decide',['a'.repeat(64),999,'approved'])).toEqual({error:'invalid'});
  expect(await rpc('supportos_tg_login_decide',['a'.repeat(64),123,'approved'])).toEqual({status:'approved'});
  expect(await rpc('supportos_tg_login_decide',['a'.repeat(64),123,'approved'])).toEqual({error:'processed'});
  expect(await state()).toMatchObject({status:'approved'});
  expect(await state(user,sid2)).toMatchObject({status:'required'});
  await pg.query("update public.supportos_users set status='active' where id=$1",[user]);
  await pg.query("insert into public.supportos_user_roles(user_id,role_id) values($1,'support')",[user]);
  await pg.exec("insert into public.supportos_categories(id,name) values('private','Internal');grant select on public.supportos_categories to authenticated;");
  await pg.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[user,JSON.stringify({session_id:sid2})]);
  await pg.exec('set role authenticated');
  expect((await pg.query('select * from public.supportos_categories')).rows).toHaveLength(0);
  await expect(pg.query('select * from public.supportos_telegram_login_challenges')).rejects.toThrow('permission denied');
  await expect(state()).rejects.toThrow('permission denied');
  await pg.exec('reset role');
  await pg.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({session_id:sid})]);
  await pg.exec('set role authenticated');
  expect((await pg.query('select * from public.supportos_categories')).rows).toHaveLength(1);
  await pg.exec('reset role');
  expect(await rpc('supportos_tg_login_cancel',[user,sid])).toBe(true);
  expect(await state()).toMatchObject({status:'rejected'});
  expect(await rpc('supportos_tg_login_begin',[user,sid,id,'b'.repeat(64),'Browser','ip',false])).toMatchObject({status:'rejected'});
  expect(await rpc('supportos_tg_link_begin',[legacy,id,sid2,'c'.repeat(64)])).toMatchObject({status:'link_required',send:true});
  expect(await rpc('supportos_tg_link_verify',['c'.repeat(64),456,'legacy'])).toEqual({status:'verified'});
  expect(await state(legacy,id)).toMatchObject({status:'link_review'});
  await expect(rpc('supportos_tg_link_review',[user,sid,sid2,true])).rejects.toThrow();
  expect((await pg.query('select * from public.supportos_telegram_links where user_id=$1',[legacy])).rows).toHaveLength(0);
  await pg.query("update public.supportos_telegram_login_challenges set status='approved',approved_at=now() where id=$1",[id]);
  await pg.query("insert into public.supportos_user_roles(user_id,role_id) values($1,'admin')",[user]);
  expect(await rpc('supportos_tg_link_review',[user,sid,sid2,true])).toBe(true);
  expect(await state(legacy,id)).toMatchObject({status:'required'});
  await expect(rpc('supportos_tg_link_review',[user,sid,sid2,true])).rejects.toThrow();
  expect(await rpc('supportos_tg_login_begin',[legacy,id,legacy,'d'.repeat(64),'Browser','ip',false])).toMatchObject({status:'pending'});
  await pg.query("update public.supportos_telegram_login_challenges set expires_at=now()-interval '1 second' where id=$1",[legacy]);
  expect(await rpc('supportos_tg_login_decide',['d'.repeat(64),456,'approved'])).toEqual({error:'expired'});
  expect(await state(legacy,id)).toMatchObject({status:'expired'});
  await pg.query('delete from auth.sessions where id=$1',[sid]);
  expect(await state()).toMatchObject({status:'invalid_session'});
 }finally{await pg.close();}
},30000);
