/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as SportsBettingRouteImport } from './routes/sports-betting'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as ProjectEmailsRouteImport } from './routes/project-emails'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BonusesRouteImport } from './routes/bonuses'
import { Route as BonusToolsRouteImport } from './routes/bonus-tools'
import { Route as BindsRouteImport } from './routes/binds'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTranslatorRouteImport } from './routes/settings/translator'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as ImportGoogleSheetsRouteImport } from './routes/import/google-sheets'
import { Route as AiTranslatorRouteImport } from './routes/ai/translator'
import { Route as AiKnowledgeRouteImport } from './routes/ai/knowledge'
import { Route as AiAssistantRouteImport } from './routes/ai/assistant'

const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsBettingRoute = SportsBettingRouteImport.update({
  id: '/sports-betting',
  path: '/sports-betting',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectEmailsRoute = ProjectEmailsRouteImport.update({
  id: '/project-emails',
  path: '/project-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesRoute = BonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusToolsRoute = BonusToolsRouteImport.update({
  id: '/bonus-tools',
  path: '/bonus-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BindsRoute = BindsRouteImport.update({
  id: '/binds',
  path: '/binds',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTranslatorRoute = SettingsTranslatorRouteImport.update({
  id: '/settings/translator',
  path: '/settings/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportGoogleSheetsRoute = ImportGoogleSheetsRouteImport.update({
  id: '/import/google-sheets',
  path: '/import/google-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTranslatorRoute = AiTranslatorRouteImport.update({
  id: '/ai/translator',
  path: '/ai/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKnowledgeRoute = AiKnowledgeRouteImport.update({
  id: '/ai/knowledge',
  path: '/ai/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai/assistant',
  path: '/ai/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/binds': typeof BindsRoute
  '/bonus-tools': typeof BonusToolsRoute
  '/bonuses': typeof BonusesRoute
  '/favorites': typeof FavoritesRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/project-emails': typeof ProjectEmailsRoute
  '/recent': typeof RecentRoute
  '/sports-betting': typeof SportsBettingRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/binds': typeof BindsRoute
  '/bonus-tools': typeof BonusToolsRoute
  '/bonuses': typeof BonusesRoute
  '/favorites': typeof FavoritesRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/project-emails': typeof ProjectEmailsRoute
  '/recent': typeof RecentRoute
  '/sports-betting': typeof SportsBettingRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/binds': typeof BindsRoute
  '/bonus-tools': typeof BonusToolsRoute
  '/bonuses': typeof BonusesRoute
  '/favorites': typeof FavoritesRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/project-emails': typeof ProjectEmailsRoute
  '/recent': typeof RecentRoute
  '/sports-betting': typeof SportsBettingRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/binds'
    | '/bonus-tools'
    | '/bonuses'
    | '/favorites'
    | '/health'
    | '/login'
    | '/project-emails'
    | '/recent'
    | '/sports-betting'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/binds'
    | '/bonus-tools'
    | '/bonuses'
    | '/favorites'
    | '/health'
    | '/login'
    | '/project-emails'
    | '/recent'
    | '/sports-betting'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/binds'
    | '/bonus-tools'
    | '/bonuses'
    | '/favorites'
    | '/health'
    | '/login'
    | '/project-emails'
    | '/recent'
    | '/sports-betting'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  BindsRoute: typeof BindsRoute
  BonusToolsRoute: typeof BonusToolsRoute
  BonusesRoute: typeof BonusesRoute
  FavoritesRoute: typeof FavoritesRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ProjectEmailsRoute: typeof ProjectEmailsRoute
  RecentRoute: typeof RecentRoute
  SportsBettingRoute: typeof SportsBettingRoute
  TranslatorRoute: typeof TranslatorRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiKnowledgeRoute: typeof AiKnowledgeRoute
  AiTranslatorRoute: typeof AiTranslatorRoute
  ImportGoogleSheetsRoute: typeof ImportGoogleSheetsRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsTranslatorRoute: typeof SettingsTranslatorRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-betting': {
      id: '/sports-betting'
      path: '/sports-betting'
      fullPath: '/sports-betting'
      preLoaderRoute: typeof SportsBettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-emails': {
      id: '/project-emails'
      path: '/project-emails'
      fullPath: '/project-emails'
      preLoaderRoute: typeof ProjectEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses': {
      id: '/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof BonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonus-tools': {
      id: '/bonus-tools'
      path: '/bonus-tools'
      fullPath: '/bonus-tools'
      preLoaderRoute: typeof BonusToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binds': {
      id: '/binds'
      path: '/binds'
      fullPath: '/binds'
      preLoaderRoute: typeof BindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/translator': {
      id: '/settings/translator'
      path: '/settings/translator'
      fullPath: '/settings/translator'
      preLoaderRoute: typeof SettingsTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/google-sheets': {
      id: '/import/google-sheets'
      path: '/import/google-sheets'
      fullPath: '/import/google-sheets'
      preLoaderRoute: typeof ImportGoogleSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/translator': {
      id: '/ai/translator'
      path: '/ai/translator'
      fullPath: '/ai/translator'
      preLoaderRoute: typeof AiTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/knowledge': {
      id: '/ai/knowledge'
      path: '/ai/knowledge'
      fullPath: '/ai/knowledge'
      preLoaderRoute: typeof AiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/assistant': {
      id: '/ai/assistant'
      path: '/ai/assistant'
      fullPath: '/ai/assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  BindsRoute: BindsRoute,
  BonusToolsRoute: BonusToolsRoute,
  BonusesRoute: BonusesRoute,
  FavoritesRoute: FavoritesRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ProjectEmailsRoute: ProjectEmailsRoute,
  RecentRoute: RecentRoute,
  SportsBettingRoute: SportsBettingRoute,
  TranslatorRoute: TranslatorRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiKnowledgeRoute: AiKnowledgeRoute,
  AiTranslatorRoute: AiTranslatorRoute,
  ImportGoogleSheetsRoute: ImportGoogleSheetsRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsTranslatorRoute: SettingsTranslatorRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
