/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslatorRouteImport } from './routes/translator'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BindsRouteImport } from './routes/binds'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTranslatorRouteImport } from './routes/settings/translator'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as ImportGoogleSheetsRouteImport } from './routes/import/google-sheets'
import { Route as AiTranslatorRouteImport } from './routes/ai/translator'
import { Route as AiKnowledgeRouteImport } from './routes/ai/knowledge'
import { Route as AiAssistantRouteImport } from './routes/ai/assistant'

const TranslatorRoute = TranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BindsRoute = BindsRouteImport.update({
  id: '/binds',
  path: '/binds',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTranslatorRoute = SettingsTranslatorRouteImport.update({
  id: '/settings/translator',
  path: '/settings/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportGoogleSheetsRoute = ImportGoogleSheetsRouteImport.update({
  id: '/import/google-sheets',
  path: '/import/google-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTranslatorRoute = AiTranslatorRouteImport.update({
  id: '/ai/translator',
  path: '/ai/translator',
  getParentRoute: () => rootRouteImport,
} as any)
const AiKnowledgeRoute = AiKnowledgeRouteImport.update({
  id: '/ai/knowledge',
  path: '/ai/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai/assistant',
  path: '/ai/assistant',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binds': typeof BindsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binds': typeof BindsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binds': typeof BindsRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/recent': typeof RecentRoute
  '/translator': typeof TranslatorRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/knowledge': typeof AiKnowledgeRoute
  '/ai/translator': typeof AiTranslatorRoute
  '/import/google-sheets': typeof ImportGoogleSheetsRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/translator': typeof SettingsTranslatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/binds'
    | '/favorites'
    | '/login'
    | '/recent'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/binds'
    | '/favorites'
    | '/login'
    | '/recent'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
  id:
    | '__root__'
    | '/'
    | '/binds'
    | '/favorites'
    | '/login'
    | '/recent'
    | '/translator'
    | '/ai/assistant'
    | '/ai/knowledge'
    | '/ai/translator'
    | '/import/google-sheets'
    | '/settings/ai'
    | '/settings/translator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BindsRoute: typeof BindsRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  RecentRoute: typeof RecentRoute
  TranslatorRoute: typeof TranslatorRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiKnowledgeRoute: typeof AiKnowledgeRoute
  AiTranslatorRoute: typeof AiTranslatorRoute
  ImportGoogleSheetsRoute: typeof ImportGoogleSheetsRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsTranslatorRoute: typeof SettingsTranslatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translator': {
      id: '/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof TranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binds': {
      id: '/binds'
      path: '/binds'
      fullPath: '/binds'
      preLoaderRoute: typeof BindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/translator': {
      id: '/settings/translator'
      path: '/settings/translator'
      fullPath: '/settings/translator'
      preLoaderRoute: typeof SettingsTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import/google-sheets': {
      id: '/import/google-sheets'
      path: '/import/google-sheets'
      fullPath: '/import/google-sheets'
      preLoaderRoute: typeof ImportGoogleSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/translator': {
      id: '/ai/translator'
      path: '/ai/translator'
      fullPath: '/ai/translator'
      preLoaderRoute: typeof AiTranslatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/knowledge': {
      id: '/ai/knowledge'
      path: '/ai/knowledge'
      fullPath: '/ai/knowledge'
      preLoaderRoute: typeof AiKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/assistant': {
      id: '/ai/assistant'
      path: '/ai/assistant'
      fullPath: '/ai/assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BindsRoute: BindsRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  RecentRoute: RecentRoute,
  TranslatorRoute: TranslatorRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiKnowledgeRoute: AiKnowledgeRoute,
  AiTranslatorRoute: AiTranslatorRoute,
  ImportGoogleSheetsRoute: ImportGoogleSheetsRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsTranslatorRoute: SettingsTranslatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
